persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Écouter sur toutes les interfaces (important pour Docker)
listener 1883 0.0.0.0

# Activer WebSocket
listener 9001 0.0.0.0
protocol websockets

# Autoriser les connexions anonymes (pour le test)
allow_anonymous true
